apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://demo_power_sense_prometheus:9090
    isDefault: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse
    jsonData:
      defaultDatabase: electricity
      host: demo_power_sense_clickhouse
      port: 8123
      protocol: http
      username: electricity
    secureJsonData:
      password: electricity

  - name: Loki
    type: loki
    access: proxy
    url: http://demo_power_sense_loki:3100
