apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:58123
    uid: clickhouse
    jsonData:
      defaultDatabase: electricity
      protocol: http
      username: electricity
    secureJsonData:
      password: electricity

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
